power <- read.table(file.choose(), sep=";", header=TRUE, stringsAsFactors=FALSE, na.strings="?")
power$Date<-as.Date(power$Date, format="%d/%m/%Y")
df<-subset(power, Date=="2007-02-01" | Date=="2007-02-02")
df$Global_active_power<-as.numeric(df$Global_active_power)
hist(df$Global_active_power, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.copy(png, file="plot1.png", width=480, height=480)
dev.off()
cat("plot1.png has been saved in", getwd())
