power <- read.table(file.choose(), sep=";", header=TRUE, stringsAsFactors=FALSE, na.strings="?")
power$Date<-as.Date(power$Date, format="%d/%m/%Y")
df<-subset(power, Date=="2007-02-01" | Date=="2007-02-02")
df$Global_active_power<-as.numeric(df$Global_active_power)
df<-transform(df, timestamp=as.POSIXct(paste(Date, Time)), "%Y-%m-%d %H:%M:%S")
df$Sub_metering_1<-as.numeric(as.character(df$Sub_metering_1))
df$Sub_metering_2<-as.numeric(as.character(df$Sub_metering_2))
df$Sub_metering_3<-as.numeric(as.character(df$Sub_metering_3))
par(mfrow=c(2,2), mar=c(4,4,2,1), oma=c(0,0,2,0))
with(df,{
plot(Global_active_power~timestamp, type="l", ylab="Global Active Power", xlab="")
plot(Voltage~timestamp, type="l", ylab="Voltage",xlab="datetime")
plot(Sub_metering_1~timestamp,type="l",xlab="", ylab="Energy sub metering")
lines(Sub_metering_2~timestamp, col="red")
lines(Sub_metering_3~timestamp, col="blue")
legend("topright",col=c("black","red","blue"),c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=1,lwd=2, bty="n") 
plot(Global_reactive_power~timestamp, type="l", ylab="Global Reactive Power", xlab="datetime")
})
dev.copy(png, file="plot4.png", width=480, height=480)
dev.off()
cat("plot4.png has been saved in", getwd())
