power <- read.table(file.choose(), sep=";", header=TRUE, stringsAsFactors=FALSE, na.strings="?")
power$Date<-as.Date(power$Date, format="%d/%m/%Y")
df<-subset(power, Date=="2007-02-01" | Date=="2007-02-02")
df$Global_active_power<-as.numeric(df$Global_active_power)
df<-transform(df, timestamp=as.POSIXct(paste(Date, Time)), "%Y-%m-%d %H:%M:%S")
plot(df$timestamp,df$Global_active_power, type="l",xlab="", ylab="Global Active Power (kilowatts)")
dev.copy(png, file="plot2.png", width=480, height=480)
dev.off()
cat("plot2.png has been saved in", getwd())
