power <- read.table(file.choose(), sep=";", header=TRUE, stringsAsFactors=FALSE, na.strings="?")
power$Date<-as.Date(power$Date, format="%d/%m/%Y")
df<-subset(power, Date=="2007-02-01" | Date=="2007-02-02")
df$Global_active_power<-as.numeric(df$Global_active_power)
df<-transform(df, timestamp=as.POSIXct(paste(Date, Time)), "%Y-%m-%d %H:%M:%S")
df$Sub_metering_1<-as.numeric(as.character(df$Sub_metering_1))
df$Sub_metering_2<-as.numeric(as.character(df$Sub_metering_2))
df$Sub_metering_3<-as.numeric(as.character(df$Sub_metering_3))
plot(df$timestamp, df$Sub_metering_1,type="l",xlab="", ylab="Energy sub metering")
lines(df$timestamp,df$Sub_metering_2, col="red")
lines(df$timestamp,df$Sub_metering_3, col="blue")
legend("topright",col=c("black","red","blue"),c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), lty=c(1,1),lwd=c(1,1)) 
dev.copy(png, file="plot3.png", width=480, height=480)
dev.off()
cat("plot3.png has been saved in", getwd())
